name: Go

on:
  push:
    branches: [ main ]
  schedule:
  - cron: "0 9 * * 1-5"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Echo
      run: echo "Hello World!!!"

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
